// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBhVAGuqQZAAb_GEFSPU2LaKCF7YNpVrQ',
    appId: '1:233800088312:web:a3aa2af1ad8c6f6427590d',
    messagingSenderId: '233800088312',
    projectId: 'fortunecookie-398509',
    authDomain: 'fortunecookie-398509.firebaseapp.com',
    databaseURL: 'https://fortunecookie-398509-default-rtdb.firebaseio.com',
    storageBucket: 'fortunecookie-398509.appspot.com',
    measurementId: 'G-QNFGY3RWHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArbuK6CwDRYnegjP5RbSvCemcitI2OLzE',
    appId: '1:233800088312:android:a65481ff845275a027590d',
    messagingSenderId: '233800088312',
    projectId: 'fortunecookie-398509',
    databaseURL: 'https://fortunecookie-398509-default-rtdb.firebaseio.com',
    storageBucket: 'fortunecookie-398509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpJWY7WXOUtSgR6oceP4ypAT3N9Ak9rnM',
    appId: '1:233800088312:ios:1679f01e2bc6e92327590d',
    messagingSenderId: '233800088312',
    projectId: 'fortunecookie-398509',
    databaseURL: 'https://fortunecookie-398509-default-rtdb.firebaseio.com',
    storageBucket: 'fortunecookie-398509.appspot.com',
    iosBundleId: 'com.sticky.fortune-cookie',
  );
}
